# Generated by Django 4.2.23 on 2025-06-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this chain",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="The template for the prompt, using {variable} syntax"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="The name of the LLM model to use", max_length=255),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai",
                        help_text="The LLM provider to use (e.g., 'openai', 'google')",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="The temperature parameter for the model"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of tokens to generate",
                        null=True,
                    ),
                ),
                (
                    "input_variables",
                    models.JSONField(
                        default=list, help_text="List of expected input variable names"
                    ),
                ),
                (
                    "output_parser",
                    models.CharField(
                        blank=True,
                        help_text="Name of LangChain output parser (e.g., 'JSONOutputParser')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this chain is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "LLM Chain",
                "verbose_name_plural": "LLM Chains",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="UUID for anonymous sessions or custom session tracking",
                        max_length=100,
                        unique=True,
                        verbose_name="session id",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="A user-friendly title for the chat",
                        max_length=200,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "llm_config",
                    models.JSONField(
                        default=dict,
                        help_text="Specific LLM configuration for this session",
                        verbose_name="LLM config",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this chat session",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "token_count",
                    models.IntegerField(blank=True, null=True, verbose_name="token count"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="For ordering in case of simultaneous writes",
                        verbose_name="order",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="django_chain.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LLMInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.TextField(verbose_name="prompt text")),
                ("response_text", models.TextField(verbose_name="response text")),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the LLM model used",
                        max_length=100,
                        verbose_name="model name",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="LLM provider (e.g., openai, google)",
                        max_length=50,
                        verbose_name="provider",
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(blank=True, null=True, verbose_name="input tokens"),
                ),
                (
                    "output_tokens",
                    models.IntegerField(blank=True, null=True, verbose_name="output tokens"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Estimated cost of the interaction in USD",
                        max_digits=10,
                        null=True,
                        verbose_name="total cost",
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Latency of the LLM API call in milliseconds",
                        null=True,
                        verbose_name="latency ms",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the interaction failed",
                        null=True,
                        verbose_name="error message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional arbitrary metadata",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the interaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Interaction Log",
                "verbose_name_plural": "LLM Interaction Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="django_chai_created_f55512_idx"),
                    models.Index(
                        fields=["user", "created_at"],
                        name="django_chai_user_id_127566_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "created_at"], name="django_chai_user_id_855317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["session_id"], name="django_chai_session_d72c30_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "timestamp"], name="django_chai_session_44c56e_idx"
            ),
        ),
    ]
