# Generated by Django 4.2.23 on 2025-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={
                "ordering": ["name", "-version"],
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("FROM_STRINGS", "Base Message"),
                    ("HUMAN", "Human Message"),
                    ("AI", "AI Message"),
                    ("SYSTEM", "System Message"),
                    ("CHAT", "Chat Message"),
                ],
                default="FROM_STRINGS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prompt",
            name="prompt_template",
            field=models.JSONField(
                default={},
                help_text="JSON representation of the LangChain prompt. Must include 'langchain_type' (e.g., 'PromptTemplate', 'ChatPromptTemplate').",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="type",
            field=models.CharField(
                choices=[
                    ("PROMPT_TEMPLATE", "String Prompt Template"),
                    ("CHAT_PROMPT_TEMPLATE", "Chat Prompt Template"),
                ],
                default="CHAT_PROMPT_TEMPLATE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User template"),
                    ("ASSISTANT", "Assistant Template"),
                    ("SYSTEM", "System Template"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("STRING", "String Message"),
                    ("MESSAGEPLACEHOLDER", "Placeholder message"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("name", "is_active"), ("name", "version")},
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="template",
        ),
        migrations.DeleteModel(
            name="PromptTemplate",
        ),
    ]
